---

# file: tasks/main.yml

- name: wxWidgets | Check is wx-config installed
  shell: command -v wx-config >/dev/null 2>&1
  register: wx_config_exists
  ignore_errors: yes

- name: wxWidgets | check version
  ansible.builtin.command:
    cmd:
      wx-config --version
  when: wx_config_exists.rc == 0
  register: wxWidgets_ver

- debug:
    msg: "CheckSum = {{ wxWidgets_ver }}"

- name: wxWidgets | Get wxWidgets sources
  become: true
  get_url: url="{{ wxWidgets_url }}" dest="{{ wxWidgets_tmp }}" timeout=180 force=no
  when: ( wx_config_exists.rc == 1 ) or ( wxWidgets_ver.stdout != '3.2.4' )
  register: wxWidgets_downloaded

- name: wxWidgets | Extract wxWidgets sources
  become: true
  unarchive: src="{{ wxWidgets_tmp }}"
             dest="/tmp"
             creates="{{ wxWidgets_build }}"
             remote_src=yes
  when: wxWidgets_downloaded.changed

- name: wxWidgets | configure wxWidgets Makefile
  ansible.builtin.command:
    chdir:
      "{{ wxWidgets_build }}"
    cmd:
      ./configure
      --prefix="{{ wxWidgets_install_dir }}"
      # --enable-webview
      # --enable-compat28
      # --with-gtk=3
      # --disable-shared
      # --enable-unicode      
  when: wxWidgets_downloaded.changed

- name: wxWidgets | make and install wxWidgets
  ansible.builtin.command:
    chdir:
      "{{ wxWidgets_build }}"
    cmd:
      make -j4 install
  become: true
  when: wxWidgets_downloaded.changed

- name: wxWidgets | cleanup tmp
  become: true
  file:
    path: "{{ wxWidgets_tmp }}"
    state: absent
  when: wxWidgets_downloaded.changed

- name: wxWidgets | cleanup tmp build
  become: true
  file:
    path: "{{ wxWidgets_build }}"
    state: absent
  when: wxWidgets_downloaded.changed
...



