---

# file: tasks/main.yml

- name: wxWidgets | Check is wx-config installed
  shell: command -v wx-config >/dev/null 2>&1
  register: wx_config_exists
  ignore_errors: yes

- name: wxWidgets | check version
  ansible.builtin.command:
    cmd:
      wx-config --version
  when: wx_config_exists.rc == 0
  register: wxWidgets_version

- name: wxWidgets | Get wxWidgets sources
  become: true
  get_url: url="{{ wxWidgets_url }}" dest="{{ wxWidgets_tmp }}" timeout=180 force=no
  when: ( wx_config_exists.rc == 1 ) or ( wxWidgets_version.stdout != "{{ wxWidgets_version }}" )
  register: wxWidgets_downloaded

- name: wxWidgets | Extract wxWidgets sources
  become: true
  unarchive: src="{{ wxWidgets_tmp }}"
             dest="/tmp"
             creates="{{ wxWidgets_build }}"
             remote_src=yes
  when: wxWidgets_downloaded.changed
  #register: wxWidgets_extract

- name: wxWidgets | configure wxWidgets Makefile
  ansible.builtin.command:
    chdir:
      "{{ wxWidgets_build }}"
    cmd:
      ./configure
      # --prefix="{{ emacs_install_dir }}"
      # --with-tree-sitter
      # --with-native-compilation=aot
      # --with-file-notification=inotify
      # --with-json
      # --without-x-toolkit
      # --without-x
  #when: wxWidgets.changed
  #register: wxWidgets_configure

- name: wxWidgets | make and install wxWidgets
  ansible.builtin.command:
    chdir:
      "{{ wxWidgets_build }}"
    cmd:
      make install
  become: true
  #when: wxWidgets_configure.changed
  #register: wxWidgets_install

- name: wxWidgets | cleanup tmp
  become: true
  file:
    path: "{{ wxWidgets_tmp }}"
    state: absent
  #when: wxWidgets_install.changed
...



